import os
import subprocess
import glob
from string import Template

# --- Configuration ---
LOCAL_MODELS_DIR = os.path.expanduser("~/.maniskill/data/tasks/grasping/mani_skill2_ycb/models")
START_OBJECT_NUM = 0
TOTAL_TIMESTEPS = "20_000_000"
IMAGE_NAME = "gitlab-registry.nrp-nautilus.io/jluo2/ucsd:latest"
MAX_PARALLELISM = 16  # Number of pods to run at once

PVC_NAME = "maniskill-pvc" 

job_template = Template("""
apiVersion: batch/v1
kind: Job
metadata:
  name: maniskill-ppo-indexed-sweep
  labels:
    app: maniskill-sweep
spec:
  parallelism: ${parallelism}
  completions: ${num_objects}
  completionMode: Indexed
  backoffLimit: 2
  template:
    metadata:
      labels:
        app: maniskill-sweep
    spec:
      restartPolicy: OnFailure
      nodeSelector:
        nvidia.com/gpu.product: NVIDIA-GeForce-RTX-2080-Ti

      containers:
      - name: runner
        image: ${image}
        imagePullPolicy: IfNotPresent
        env:
        - name: WANDB_API_KEY
          valueFrom:
            secretKeyRef:
              name: jluo-wandb
              key: WANDB_API_KEY
        resources:
          limits:
            cpu: "1"
            memory: 8Gi
            nvidia.com/gpu: 1
            ephemeral-storage: 40Gi
          requests:
            cpu: "1"
            memory: 8Gi
            nvidia.com/gpu: 1
            ephemeral-storage: 40Gi
        
        # --- MOUNT CONFIGURATION ---
        volumeMounts:
        # 1. Mount the PVC to /data
        - name: persistent-storage
          mountPath: /data
        
        # 2. (Optional) Keep Shm for PyTorch speed
        - name: dshm
          mountPath: /dev/shm
        
        command: ["/bin/bash", "-lc"]
        args:
        - |
          set -euo pipefail
          
          # 1. Define the object list (generated by Python)
          OBJECTS=(${objects_list})
          
          # 2. Get this pod's assigned object using the index
          object_name=$${OBJECTS[$$JOB_COMPLETION_INDEX]}
          
          echo "Starting ManiSkill PPO for Index: $$JOB_COMPLETION_INDEX, Object: $$object_name"
          
          # Setup Environment
          if [ ! -d "/opt/ManiSkill" ]; then
            echo "Cloning ManiSkill repository..."
            git clone --depth 1 --branch main "https://github.com/justinluo4/ManiSkill.git" /opt/ManiSkill
          fi
          
          cd /opt/ManiSkill
          
          # Install dependencies
          echo "Installing ManiSkill dependencies..."
          conda install -y python=3.12
          pip install --upgrade pip
          pip install -e .
          pip install torch tensorboard
          
          # Download physx GPU binary via sapien
          echo "Downloading physx GPU binary..."
          python -c "import sapien.physx as physx; physx.enable_gpu()" || true
          mkdir -p /root/.maniskill/data/tasks/grasping/mani_skill2_ycb
          if [ ! -L "/root/.maniskill/data/tasks/grasping/mani_skill2_ycb/models" ]; then
            ln -s /data/models /root/.maniskill/data/tasks/grasping/mani_skill2_ycb/
          fi

          echo "Running PPO (use_decomp)..."
          python examples/baselines/ppo/ppo.py \\
            --env_id="CustomPick-v1" \\
            --num_envs=1024 \\
            --update_epochs=8 \\
            --num_minibatches=32 \\
            --total_timesteps="${timesteps}" \\
            --eval_freq=10 \\
            --num-steps=100 \\
            --track \\
            --pick_object_name "$$object_name" \\
            --wandb_project_name="maniskill-ppo-runs" \\
            --partial_reset \\
            --use_decomp

          echo "Running PPO (no decomp)..."
          python examples/baselines/ppo/ppo.py \\
            --env_id="CustomPick-v1" \\
            --num_envs=1024 \\
            --update_epochs=8 \\
            --num_minibatches=32 \\
            --total_timesteps="${timesteps}" \\
            --eval_freq=10 \\
            --num-steps=100 \\
            --track \\
            --pick_object_name "$$object_name" \\
            --wandb_project_name="maniskill-ppo-runs" \\
            --partial_reset

      volumes:
      # --- VOLUME DEFINITION ---
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: ${pvc_name}
      - name: dshm
        emptyDir:
          medium: Memory
""")

def main():
    if not os.path.exists(LOCAL_MODELS_DIR):
        print(f"Error: Models directory not found at {LOCAL_MODELS_DIR}")
        exit(1)

    subdirs = glob.glob(os.path.join(LOCAL_MODELS_DIR, "*/"))
    subdirs.sort()
    
    # Filter objects based on START_OBJECT_NUM
    final_objects = []
    for object_dir in subdirs:
        name = os.path.basename(os.path.normpath(object_dir))
        try:
            num = int(name[:3])
            if num >= START_OBJECT_NUM:
                final_objects.append(name)
        except ValueError:
            if START_OBJECT_NUM == 0:
                final_objects.append(name)

    if not final_objects:
        print("No objects to process.")
        return

    # Create bash array string: "obj1" "obj2" "obj3"
    objects_list_str = " ".join([f'"{name}"' for name in final_objects])

    print(f"Submitting Indexed Job for {len(final_objects)} objects with parallelism {MAX_PARALLELISM}...")
    
    # Delete previous job
    subprocess.run(['kubectl', 'delete', 'job', 'maniskill-ppo-indexed-sweep', '--ignore-not-found=true'])

    k8s_manifest = job_template.substitute(
        num_objects=len(final_objects),
        parallelism=MAX_PARALLELISM,
        objects_list=objects_list_str,
        timesteps=TOTAL_TIMESTEPS,
        image=IMAGE_NAME,
        pvc_name=PVC_NAME
    )

    process = subprocess.Popen(['kubectl', 'apply', '-f', '-'], stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
    stdout, stderr = process.communicate(input=k8s_manifest)

    if process.returncode != 0:
        print(f"Error submitting Job: {stderr}")
    else:
        print("Job submitted successfully. Monitor with: kubectl get pods -l app=maniskill-sweep")

if __name__ == "__main__":
    main()
